# Generated by Django 4.1.5 on 2023-01-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.SmallAutoField(
                max_length=6, primary_key=True, serialize=False
            ),
        ),
    ]
